name: Pull Request ChatGPT review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_pr_reviewer:
    uses: domoapps/doc-reviewer-action/.github/workflows/action.yml@v1.0.0
    secrets:
      CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}
      CHATGPT_MODEL: ${{ secrets.CHATGPT_MODEL }}
      API_KEY: ${{ secrets.API_KEY }}
