name: Pull Request ChatGPT review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai_pr_reviewer:
    uses: DomoApps/doc-reviewer-actions/.github/workflows/action.yml@main
    secrets:
      CHATGPT_KEY: ${{ secrets.CHATGPT_KEY }}
      CHATGPT_MODEL: ${{ secrets.CHATGPT_MODEL }}
      API_KEY: ${{ secrets.API_KEY }}
